# Generated by Django 5.2.1 on 2025-11-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
