# Generated by Django 5.2.1 on 2025-11-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_notificationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={},
        ),
    ]
